"""
Strict Pydantic Schemas for ADK Tools, Guided Recovery, and Agent Messaging.
Guarantees 100% type validation, explicit schema documentation, and guided LLM error recovery.
"""

from typing import Dict, Any, List, Optional, Literal
from pydantic import BaseModel, Field


class ToolErrorResponse(BaseModel):
    """Guided error recovery schema returned to LLM when tool execution encounters exceptions."""
    status: Literal["ERROR"] = "ERROR"
    error_type: str = Field(description="Name or category of the exception encountered")
    error_message: str = Field(description="Human-readable description of the error cause")
    recovery_instruction: str = Field(description="Explicit guided instruction directing the LLM on how to adjust parameters or retry")


class ArticleSnippet(BaseModel):
    """Structured article snippet returned by news search tools."""
    title: str = Field(description="Title of the news article or paper")
    url: str = Field(description="Source URL")
    snippet: str = Field(description="Key summary or extract from the article")
    credibility_score: float = Field(default=0.92, description="Source credibility score between 0.0 and 1.0")


class SearchBundleSchema(BaseModel):
    """Schema returned by web search tool containing verified articles and query counts."""
    query: str = Field(description="Original search query executed")
    results_count: int = Field(description="Number of articles returned")
    articles: List[ArticleSnippet] = Field(description="List of verified article snippets")


class HeroImageResultSchema(BaseModel):
    """Schema returned by hero image generator tool."""
    title: str = Field(description="Article title used for visual design")
    domain: str = Field(description="Article domain or topic")
    category_label: str = Field(description="Dynamic category badge rendered on image")
    hero_image_url: str = Field(description="Public HTTP URL of the generated hero image on GCS")
    gcs_uri: str = Field(description="Google Cloud Storage gs:// URI")
    status: Literal["GENERATED_AND_UPLOADED"] = "GENERATED_AND_UPLOADED"


class SectionSchema(BaseModel):
    """Structured body section in blog article."""
    heading: str = Field(description="Section heading title")
    text: str = Field(description="Section body content paragraph")


class ArticleDraftSchema(BaseModel):
    """Complete article draft schema generated by domain writer agents."""
    task_id: str = Field(description="Unique task identifier")
    session_id: str = Field(description="Session identifier")
    title: str = Field(description="Financial Times benchmark article title")
    domain: Literal["Politicals", "Economics", "Science"] = Field(description="Topic domain")
    hero_image_url: str = Field(description="GCS public URL for the hero image")
    introduction: str = Field(description="Article introduction paragraph")
    body_sections: List[SectionSchema] = Field(description="Key analytical body sections")
    conclusion: str = Field(description="Conclusion and strategic roadmap")
    editorial_opinion: str = Field(description="Editorial commentary section")


class RubricScoresSchema(BaseModel):
    """Quantitative quality evaluation scores produced by Judge Agent."""
    coherence: float = Field(ge=0.0, le=1.0, description="Logical flow and analytical depth (0.0 - 1.0)")
    alignment: float = Field(ge=0.0, le=1.0, description="Topic alignment and accuracy (0.0 - 1.0)")
    fluency: float = Field(ge=0.0, le=1.0, description="Readability and professional tone (0.0 - 1.0)")
    image_relevance: float = Field(ge=0.0, le=1.0, description="Hero image relevance to article title (0.0 - 1.0)")
    image_quality: float = Field(ge=0.0, le=1.0, description="Visual design, contrast, and branding quality (0.0 - 1.0)")
    composite_score: float = Field(ge=0.0, le=1.0, description="Weighted composite evaluation score")


class JudgeEvaluationSchema(BaseModel):
    """Complete Judge Agent evaluation and compliance audit record."""
    judgment_id: str = Field(description="Unique judgment identifier")
    task_id: str = Field(description="Task identifier")
    session_id: str = Field(description="Session identifier")
    decision: Literal["APPROVED", "REJECTED"] = Field(description="Quality gate decision")
    rubric_scores: RubricScoresSchema = Field(description="Rubric score breakdown")
    critique: str = Field(description="Detailed qualitative evaluation and rationale")
    required_revisions: List[str] = Field(default_factory=list, description="List of required revisions if rejected")
    bigquery_logged: bool = Field(default=True, description="BigQuery persistent audit status")
    gcs_archived: bool = Field(default=True, description="GCS JSON log archive status")


class DraftBlogResultSchema(BaseModel):
    """Complete multi-agent workflow draft result returned to root_orchestrator."""
    status: Literal["CANDIDATE_READY_FOR_REVIEW", "ERROR"] = "CANDIDATE_READY_FOR_REVIEW"
    task_id: str = Field(description="Task identifier")
    session_id: str = Field(description="Session identifier")
    domain: str = Field(description="Article domain")
    title: str = Field(description="Article title")
    article_text: str = Field(description="Full formatted markdown article text")
    hero_image_url: str = Field(description="Public GCS hero image URL")
    judge_audit: JudgeEvaluationSchema = Field(description="Judge evaluation audit record")


class PublishBlogResultSchema(BaseModel):
    """Result schema for blog post publication to GCS."""
    status: Literal["PUBLISHED", "ERROR"] = "PUBLISHED"
    article_id: str = Field(description="Unique article identifier")
    session_id: str = Field(description="Session identifier")
    title: str = Field(description="Published article title")
    gcs_uri: str = Field(description="gs:// Cloud Storage URI where article is stored")
    public_url: str = Field(description="Public HTTP URL of published article JSON payload")
